### ISSUE TITLE
error related to pydantic 2.6.4

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-schema-models#54]
This is happening on pydantic 2.6.4. Let's update the minimum version to `>=2.7.

Repro:
1. install aind-data-schema-models with pydantic 2.6
2. `from aind_data_schema_models.registries import Registry`

```
pydantic.errors.PydanticUserError: Field 'registry' defined on a base class was overridden by a non-annotated attribute. All field definitions, including overrides, require a type annotation.
```

**Comment by dbirman** [comment]
I spent some time on this -- I'm confused about why it happens because the fields in map_registry are already Annotated, and changing the way they're annotated in various ways has no effect or leads to other bugs. That makes me think it's an actual bug that was fixed, although a quick search of the release notes doesn't lead to anything. I'm just going to bump to 2.7 rather than spend more time on it.
